edp:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres') }}"
      port: 5432
      user: "{{ env_var('EDP_PG_USER') }}"
      password: "{{ env_var('EDP_PG_PASSWORD') }}"
      dbname: etl
      schema: public
      threads: 2
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres') }}"
      port: 5432
      user: "{{ env_var('EDP_PG_USER') }}"
      password: "{{ env_var('EDP_PG_PASSWORD') }}"
      dbname: etl
      schema: public
      threads: 2
